### ISSUE TITLE
Latest Release Issue

### ISSUE THREAD

**Issue by jabraga** [nmolinos/csv2excel#10]
I am not sure if you are aware that the latest version 1.1.0 when downloaded is getting blocked by virus scanners with virus: 
"Trojan:Win32/Sabsik.FL.B!ml".

Our other issue is that your tool crashes converting our tab delimited files when the first character of a any field contains the " (double quote) character but the last character is not, or is not wrapped with the correct number of " characters.  I do not see in your command line options a switch for a field wrapper /  delimiter.    In our case we would like if your tool ignored all field wrapper / delimiters, not sure if that is possible?

Example data:
12345<tab>"USE BY" TODAY<tab>HELLO

Here is what we are what we are using now:
C:\Flanagan\bin>csv2excel.exe -c "\t" -i C:\tmp\csv.tmp

Unhandled Exception: Microsoft.VisualBasic.FileIO.MalformedLineException: Line 1 cannot be parsed using the current Delimiters.
   at Microsoft.VisualBasic.FileIO.TextFieldParser.ParseDelimitedLine()
   at Microsoft.VisualBasic.FileIO.TextFieldParser.ReadFields()
   at csv2excel.Program.writeToWorkbook(String outputFile, String outputData, String columnDelimiter, String lineDelimiter, Boolean textOnly, String format)
   at csv2excel.Program.Main(String[] args)

It would be great if we specifiy (-w specifies field wrappers):
csv2excel -c "\t" -w "" -i C:\tmp\csv.tmp

**Comment by nmolinos** [comment]
Hi @jabraga - lots of false positives being thrown by A/V tools.  All code and libraries are in the repository - if you can help narrow it down or get whitelisted by the A/V tool in question that would be helpful.  Otherwise...open to suggestions on how to resolve.

As far as the text qualifier issue, I'll take a closer look when I can, but in the meantime can you tell me if the version being merged in by [this pull request](https://github.com/nmolinos/csv2excel/pull/8) fixes that issue?  It uses a different parsing mechanism which may work for your use case.  Note: you'll need to clone the source repo and build the solution as the author of that one didn't include pre-built binaries.

**Comment by jabraga** [comment]
I looked at the pull request to see if there was anything in that thread that would help but I do not see that.  Your tool would require another option to pass a column wrapper like -w "?".  There are instances where data may contain " character as data itself not as the column wrapper character.  Once this happens you get the error above if the " is the first character after the column delimiter.  As far as the virus check I am not sure what is going on there since we downloaded a version on 2022-04-07 and the scanners did not complain, only the latest version.

**Comment by nmolinos** [comment]
A/V false positives resolved in [1.1.1](https://github.com/nmolinos/csv2excel/releases/tag/v1.1.1).  Disabling compression in FodeWeavers.xml did the trick (for all but one no-name A/V scanner on VirusTotal).  I will keep this open to check out the text qualifier request later

**Comment by jabraga** [comment]
Thanks that did the trick for the Virus Scanner.  When you have a chance to look into the column wrapper character option would be awsome.  Our current utility is no longer supported with the upgrade we are in progress of.

**Comment by nmolinos** [comment]
@jabraga Please try out the [2.0.0 release](https://github.com/nmolinos/csv2excel/releases/tag/v2.0.0) and let me know how it works for you.

**Comment by jabraga** [comment]
yes that is working great. thanks.
