### ISSUE TITLE
Convert a folder with multiple csv files?

### ISSUE THREAD

**Issue by kurzpc** [nmolinos/csv2excel#12]
Hello,

how can I convert a folder with multiple csv files? 

I tried it that way but unfortunately it did not work. 
`csv2excel.exe -i E:\test\*.csv`

**Comment by nmolinos** [comment]
Something like the following should work:
`for /r path/to/folder %f in (*.csv) do csv2excel.exe -i "%f"`

From https://stackoverflow.com/questions/14237548/batch-script-run-command-on-each-file-in-directory
