### ISSUE TITLE
blank lines

### ISSUE THREAD

**Issue by FirmianaMarsili** [nmolinos/csv2excel#14]
hello,thank you for your tool.
on `Program` Line.158,if `ReadFields`encounters blank lines, they are skipped and the next non-blank line is returned.
whether to consider adding a new command line,using `ReadLine` to parse rows.

**Comment by FirmianaMarsili** [comment]
[sfc64-testset-2.csv](https://github.com/nmolinos/csv2excel/files/11098910/sfc64-testset-2.csv)
yes, v1.1.1 meets my needs
![output](https://user-images.githubusercontent.com/35676922/228493160-dd11d629-3577-4fcd-8f90-07906588bd96.png)

**Comment by FirmianaMarsili** [comment]
this is v2.0.0
![v2 0 0](https://user-images.githubusercontent.com/35676922/228494078-33c72b39-f6e5-4313-8e02-0b09f82302d9.png)

**Comment by nmolinos** [comment]
I think your best bet is to continue using 1.1.1 for now as I don't plan to bring that functionality back for the time being.  I will mention though - that if you want to preserve blank lines like that (and I believe this is true of other tools that handle CSVs), you will typically want to have the column delimiter present on the line.  If those blank lines in your CSV had just a comma, the lines would be preserved.
