### ISSUE TITLE
Enhancements - Auto adjustment about Column size

### ISSUE THREAD

**Issue by bovirus** [nmolinos/csv2excel#15]
@nmolinos 

Thanks a lot for your progra,m.

Could be possible to add as option the autozise of column width?

Thanks.

**Comment by bovirus** [comment]
@nmolinos

Sorry but I'm not able to identify how to change source code to do that.

**Comment by nmolinos** [comment]
@bovirus Please see if this works for you with the new "-r" command-line option: https://github.com/nmolinos/csv2excel/releases/tag/v.2.1.0

**Comment by bovirus** [comment]
@nmolinos 

Thanks.
It work perfectly.

**Comment by bovirus** [comment]
@nmolinos 

Please close this ticket.
