### ISSUE TITLE
Marks all MS Excel data cells as text

### ISSUE THREAD

**Issue by bdlightner** [nmolinos/csv2excel#2]
Great program but all resultant MS Excel cells are marked as "text", requiring manual conversion, one column at a time, using "Data->Text to Columns" if the data is numeric.  How difficult to add an option to convert all output cells into "numbers"?  In fact, "text" cells formatted as "numbers" seem to be treated as "text" anyway.

http://www.lightner.net/csv2excel_example.gif

**Comment by nmolinos** [comment]
Thanks for the suggestion, I'll take a look after the long weekend!

**Comment by yoavsapir** [comment]
If this change is possible, it would be a great addition.

**Comment by nmolinos** [comment]
Please try the latest version to see if that works for you.  The previous behavior can be obtained by including a new command line parameter "-t" to force all fields to Text.

**Comment by bdlightner** [comment]
Thanks for working on this.  IMHO a cell format of "General" is much better than "Text".

However the new behavior is not looking good!  Certain values are getting corrupted.

My test case was as follows...

% type xx.csv
Time,K
6.5563904,12.13969
6.55639552,12.13969
6.55640064,12.1397
6.55640576,12.1397
6.55641088,12.1397
6.556416,12.1397
6.55642112,12.1397
6.55642624,12.1397
6.55643136,12.1397
6.55643648,12.1397
6.5564416,12.1397
6.55644672,12.1397
6.55645184,12.1397
6.55645696,12.1397
6.55646208,12.1397
6.5564672,12.1397

% csv2excel -i xx.csv -o xx.xlsx -c , -f xlsx

The resultant Excel spreadsheet shows this!!!

% start xx.xlsx
Time | K
6.55639 | 12.13969
6.556396 | 12.13969
6.556401 | -1
6.556406 | -1
6.556411 | -1
6.556416 | -1
6.556421 | -1
6.556426 | -1
6.556431 | -1
6.556436 | -1
6.556442 | -1
6.556447 | -1
6.556452 | -1
6.556457 | -1
6.556462 | -1
6.556467 | -1

What's up with the cells containing "-1"?

**Comment by nmolinos** [comment]
Ah!  I see the problem.  I first started trying to build the change out so that you could specify the date formats for date columns, but that did not work at all so I took that option out.  I left the code that attempts to distinguish between numbers and dates though, so that's where this is getting hung up.  See this screenshot:

![image](https://user-images.githubusercontent.com/4980099/42354772-e8d13064-807d-11e8-8183-dd5873a3fd3e.png)

I'll remove the offending code and commit those changes shortly.

**Comment by nmolinos** [comment]
Ok, change is in...please let me know if this works for you now.

**Comment by bdlightner** [comment]
Thanks!  Works perfectly for me now, both with the test case I posted here and with a CSV file with 1 million rows of data.
