### ISSUE TITLE
the pipe character as a delimiter?

### ISSUE THREAD

**Issue by harvoni** [nmolinos/csv2excel#3]
hi, this is a very helpful script. question: how do I put in the pipe character ( | ) as a delimiter? I tried

csv2excel.exe -i input.csv -c \| -l \r\n

but then the script will not recognize any commands after the |. Many thanks!

**Comment by nmolinos** [comment]
Hi Harvoni,

It works if you wrap the pipe character with double-quotes:

csv2excel.exe -i input.csv -c "|" -l "\r\n"

Let me know if you have any other issues.

Thanks
