### ISSUE TITLE
Can't build release

### ISSUE THREAD

**Issue by Leonetienne** [nmolinos/csv2excel#4]
Hey, first off thanks for creating this awesome simple tool! Really saved my bum today!

It works gracefully! Sadly i just can't build a release build, it can't find the HSSFWorkbook, etc.. references.

Never worked with HSSF before, would be a nice touch being able to build a release.

Thanks again for this absolute lifesaver

**Comment by nmolinos** [comment]
Hi @Leonetienne  - Thanks for the feedback!  I'm glad you found the tool useful.  Please try building a Release version again and let me know if you still have trouble.
