### ISSUE TITLE
Problem with UTF-8 

### ISSUE THREAD

**Issue by cs-03** [nmolinos/csv2excel#5]
Hello There

I've got a problem with csv2excel: If there is, for example, an ä, ü, ö in the csv file, it doesn't converts it. 
The problem is, that utf-8 is uses here, is there any possible way that I can change this to, for example unicode? 

Tank you and Kind Regards
Cyrill

**Comment by nmolinos** [comment]
I'm not seeing any issues with UTF-8 characters if the file is encoded as UTF-8.  See screenshots showing the output of File.ReadAllText(inputFile) (and confirmed it shows up in the resulting XLSX fine):

![image](https://user-images.githubusercontent.com/4980099/84691014-49b5e000-aef8-11ea-817f-d38fd123e8a2.png)

![image](https://user-images.githubusercontent.com/4980099/84691027-4d496700-aef8-11ea-8281-5845a6e667ab.png)

**Comment by cs-03** [comment]
First, thanks for replying, but this wasn't exactly my problem. 
The Problem is, if I convert it from .csv into .xslx, letters like ä, ü, ö. don't convert. Here is an Example of it: 
![image](https://user-images.githubusercontent.com/66954966/84772169-d8029280-afda-11ea-8381-b0d1ef43dcb5.png)
.csv file: 
![image](https://user-images.githubusercontent.com/66954966/84772236-f2d50700-afda-11ea-88e6-4e701d7cad10.png)
convertet .xslx file: 
![image](https://user-images.githubusercontent.com/66954966/84772269-fcf70580-afda-11ea-9b76-d67aec7a1e10.png)

I did just assume the codec was some Problem, but i'm not really sure what it exactly is, becauce it only happens if I convert it with csv2excel. 

Do you have any idea what the Problem could be? 

Thank you and Kind Regards 
Cyrill

**Comment by nmolinos** [comment]
Can you confirm you are saving the CSV file as UTF-8?  
![image](https://user-images.githubusercontent.com/4980099/84806949-5bac8700-afbb-11ea-906c-e251d5897e6c.png)

**Comment by cs-03** [comment]
I'm not sure if i'm doing something wrong, but when I Save the .csv like this, 
![image](https://user-images.githubusercontent.com/66954966/84910072-b971c980-b0b6-11ea-9775-09a827ea9e8a.png)
then it's shows it in the notepad++ as ANSI
![image](https://user-images.githubusercontent.com/66954966/84910157-d1e1e400-b0b6-11ea-95bf-fa69c1521bbb.png)

Am I doing something wrong while saving the File?

**Comment by nmolinos** [comment]
I would leave those options alone and just change this when saving.  I am closing this ticket as it's not an issue with csv2excel.  Thanks

![image](https://user-images.githubusercontent.com/4980099/84938245-cb8d4100-b091-11ea-90bb-841a17b8ba67.png)
