### ISSUE TITLE
Problems with ñÑ and accented vowels

### ISSUE THREAD

**Issue by Yakano** [nmolinos/csv2excel#6]
Hello

I hope that csv2excel helps me to transform some old lists to excel, but something is wrong with the words in Spanish.

In what format must the special characters be in order to include them correctly in xlsx format?

I have tried Ascii (Dos) and Ansi (Windows) and neither has worked  because "Ñ" (and others) are changed by a question mark "�".

Thank you.

**Comment by nmolinos** [comment]
Hi Yakano,

Please refer to this previous thread for instructions on using a file saved with UTF-8 encoding:

[https://github.com/nmolinos/csv2excel/issues/5](https://github.com/nmolinos/csv2excel/issues/5)

Thanks,

Nico
