### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by sebirello** [nmolinos/csv2excel#9]
Hello @nmolinos: 

I have just scanned your tool @VirusTotal:
https://www.virustotal.com/gui/file/67a7edb83b227c81ece0d4efb52f396b600a2cb9ae243a3b1f495cc27f66f7fb/behavior/C2AE

Some scanners are reporting the tool as malicious and it is contacting an ip address?
![image](https://user-images.githubusercontent.com/26463630/161757480-29adf997-8093-479c-a619-37163677a508.png)

Thanks for the feedback!
Greetings!

**Comment by nmolinos** [comment]
Not sure where this is coming from.  I scanned the individual library DLL's I am using and the only one that come up with anything even remotely similar was `ICSharpCode.SharpZipLib.dll`.  I would appreciate if you could try building the solution yourself and scan the resulting binary to see if you get similar results from that to rule out anything from my build environment.

**Comment by nmolinos** [comment]
I found that same IP being reached out to by the following tools.  If you have any more information on this please feel free to reach out, but in the meantime I'm going to close this issue as a false positive from SysInternals.

Apple's Software Updater:
https://www.virustotal.com/gui/file/0682eef4ae722d6dad6b0c41f530d86e44f094f8487105372d5a03e0f0a437e9/behavior/Microsoft%20Sysinternals

A tool named ExplorerPatcher:
https://www.virustotal.com/gui/file/950a1eb9698f3c48f141c748cd8a653a6adb64a01c7cb754e3152ce5534223bf/behavior/Microsoft%20Sysinternals

**Comment by sebirello** [comment]
Alright, thank you, I too think it is a false positive.

**Comment by nmolinos** [comment]
@sebirello I made a small change that disables compression of the Fody Weaver package (results in a binary that is 3x larger) but it alleviates all but one no-name A/V scanner on VirusTotal.  https://github.com/nmolinos/csv2excel/releases/tag/v1.1.1

**Comment by sebirello** [comment]
Perfect, thank you for your commitment!
